import type { Profile } from "./types";

/** Diamond Light Source — sci-react-ui's DiamondDS theme.
 *
 *  Role positions follow this tool's own surface/container/solid/text
 *  standard, the same one `generic` uses. `seedPalette` and `family` hold
 *  the real values shipped in DiamondDSTokens.css, so seeding from one of
 *  Diamond's own intents checks "does this land near what I'd have
 *  chosen" — the positions are the tool's, the palette is Diamond's.
 *
 *  `accent` and `solid` swap which one sits further out between light and
 *  dark: a solid fill reads as itself from chroma alone and wants less
 *  luminance separation in dark mode, while `accent`, the smaller, quieter
 *  role beside it, needs more. See `generic.ts` for the full reasoning.
 *
 *  Curves are shared with `generic`, tuned once against a sweep of
 *  Material's 19 hues — Diamond's backgrounds are close enough that
 *  re-tuning from scratch would just rediscover the same numbers. */
export const diamondProfile: Profile = {
  id: "diamond",
  name: "Diamond Light Source (DiamondDS)",
  description:
    "The --ds-* role set from @diamondlightsource/sci-react-ui, with the nine shipped intents loaded for cross-checking.",
  provenance:
    "Role positions follow this tool's own surface/container/solid/text standard. seedPalette and family below are the real values from sci-react-ui v0.6.2.",
  scaleSize: 12,

  modes: {
    light: {
      background: "#f6f6f9",
      surface: "#ffffff",
      onSurface: "#1a1c23",
      targetLc: [3, 8, 16, 30, 45, 58, 66, 75, 85, 90, 94, 98],
      chromaMultiplier: [0.12, 0.24, 0.4, 0.6, 1.0, 1.15, 1.1, 1.0, 0.9, 0.8, 0.68, 0.55],
      selector: ':root, [data-mode="light"]',
    },
    dark: {
      background: "#0e1017",
      surface: "#161820",
      onSurface: "#e8eaf0",
      targetLc: [3, 8, 15, 24, 34, 48, 62, 74, 84, 90, 94, 98],
      chromaMultiplier: [0.3, 0.55, 0.78, 0.95, 1.2, 1.1, 1.0, 0.85, 0.75, 0.65, 0.55, 0.45],
      selector: '[data-mode="dark"]',
    },
  },

  roles: [
    {
      key: "containerLow",
      label: "Container low",
      index: { light: 0, dark: 0 },
      usage: "surface",
      requirement: "none",
      cssVar: "--ds-{intent}-container-low",
      description: "Quietest tinted surface. Extrapolated — no shipped precedent.",
    },
    {
      key: "container",
      label: "Container",
      index: { light: 1, dark: 1 },
      usage: "surface",
      requirement: "none",
      needsForeground: true,
      cssVar: "--ds-{intent}-container",
      foregroundCssVar: "--ds-on-{intent}-container",
      description: "Quiet semantic surface: standard alerts, outlined buttons, status chips.",
    },
    {
      key: "containerHigh",
      label: "Container high",
      index: { light: 2, dark: 2 },
      usage: "surface",
      requirement: "none",
      cssVar: "--ds-{intent}-container-high",
      description: "Raised or hovered container. Extrapolated — no shipped precedent.",
    },
    {
      key: "accent",
      label: "Accent",
      index: { light: 4, dark: 7 },
      usage: "boundary",
      requirement: "non-text",
      cssVar: "--ds-{intent}-accent",
      description: "Supporting emphasis: container borders, focused input outlines, the focus ring.",
    },
    {
      key: "solid",
      label: "Solid",
      index: { light: 6, dark: 4 },
      usage: "surface",
      requirement: "non-text",
      needsForeground: true,
      cssVar: "--ds-{intent}-solid",
      foregroundCssVar: "--ds-on-{intent}-solid",
      description: "Filled interactive surface: contained buttons, filled alerts and chips.",
    },
    {
      key: "base",
      label: "Base",
      index: { light: 9, dark: 9 },
      usage: "text",
      requirement: "body",
      needsForeground: true,
      cssVar: "--ds-{intent}",
      foregroundCssVar: "--ds-on-{intent}",
      description: "The default semantic colour: coloured text, icons, progress bars, text-button labels.",
    },
    {
      key: "emphasis",
      label: "Emphasis",
      index: { light: 10, dark: 10 },
      usage: "boundary",
      requirement: "non-text",
      cssVar: "--ds-{intent}-emphasis",
      description: "Stronger emphasis for pressed and active borders. Not 'darker' — lighter in dark mode.",
    },
  ],

  separationRoles: ["container", "solid", "base"],

  cssHeader:
    "/* Generated by Colour Forge. Review before pasting into DiamondDSTokens.css —\n   nothing here is written back to any file automatically. */",

  /** The shipped intents' own `solid` values, in light mode. Seeding from one
   *  of these regenerates that intent's whole role set, which is how you check
   *  whether the curves still reproduce what Diamond actually ships — and the
   *  natural starting point for a new intent meant to sit alongside them. */
  seedPaletteLabel: "Diamond's shipped intents (light solid)",
  seedPalette: [
    { name: "primary", hex: "#3f63c9" },
    { name: "secondary", hex: "#0a858e" },
    { name: "tertiary", hex: "#b0008e" },
    { name: "brand", hex: "#2f3b63" },
    { name: "danger", hex: "#d63c41" },
    { name: "warning", hex: "#e97b12" },
    { name: "success", hex: "#1b8834" },
    { name: "info", hex: "#4d72dd" },
    { name: "highlight", hex: "#fcd021" },
  ],

  /** Real values read out of DiamondDSTokens.css. `containerHigh` and
   *  `containerLow` are absent rather than guessed: they do not exist yet for
   *  any shipped intent. */
  family: [
    {
      name: "primary",
      light: { base: "#2a4db8", container: "#e5ebff", solid: "#3f63c9" },
      dark: { base: "#8aa7ff", container: "#1b2c5f", solid: "#3f63c9" },
    },
    {
      name: "secondary",
      light: { base: "#007b84", container: "#ddf3f5", solid: "#0a858e" },
      dark: { base: "#58d6de", container: "#0d3338", solid: "#0a858e" },
    },
    {
      name: "tertiary",
      light: { base: "#950078", container: "#f8e0f2", solid: "#b0008e" },
      dark: { base: "#e080cc", container: "#3a0e30", solid: "#9a007c" },
    },
    {
      name: "brand",
      light: { base: "#202945", container: "#e4e8f4", solid: "#2f3b63" },
      dark: { base: "#aabdff", container: "#202945", solid: "#3a4a78" },
    },
    {
      name: "danger",
      light: { base: "#ae1e13", container: "#fde7e5", solid: "#d63c41" },
      dark: { base: "#ff9088", container: "#3a1613", solid: "#d63c41" },
    },
    {
      name: "warning",
      light: { base: "#a95703", container: "#fef0df", solid: "#e97b12" },
      dark: { base: "#ffb067", container: "#382006", solid: "#f07a13" },
    },
    {
      name: "success",
      light: { base: "#137329", container: "#d4f3df", solid: "#1b8834" },
      dark: { base: "#6fd88a", container: "#10341a", solid: "#23913c" },
    },
    {
      name: "info",
      light: { base: "#355ec9", container: "#e9efff", solid: "#4d72dd" },
      dark: { base: "#9fb7ff", container: "#1b2b57", solid: "#4d72dd" },
    },
    {
      name: "highlight",
      light: { base: "#e5b800", container: "#fef4cc", solid: "#fcd021" },
      dark: { base: "#fddc60", container: "#352b00", solid: "#e5b800" },
    },
  ],
};
