import { buildDraft } from "../color/scale";
import { MATERIAL_500, MUI_DEFAULT_INTENTS } from "./material";
import type { Profile, SeededIntent } from "./types";

/** A design-system-agnostic role set.
 *
 *  Six roles that most token systems have some version of, named for how
 *  they are used rather than for any one library's vocabulary. The curves
 *  are a defensible starting point rather than a fit to real tokens — if you
 *  have a shipped palette, fitting these arrays to it (as the Diamond
 *  profile does) is what makes the output land on values you would have
 *  chosen by hand. */
const base: Omit<Profile, "family"> = {
  id: "generic",
  name: "Generic (design-system agnostic)",
  description:
    "Six usage-named roles and a neutral CSS naming convention. The starting point when you are not working in a system the tool already knows.",
  provenance:
    "Curves are a reasoned starting point, not fitted to a shipped palette — adjust the targets to match your own tokens. The comparison family is derived by this tool from MUI's default intent colours (Material Design 2), not values MUI itself ships per role.",
  scaleSize: 12,

  modes: {
    light: {
      background: "#fbfbfd",
      surface: "#ffffff",
      onSurface: "#16181d",
      targetLc: [3, 8, 16, 30, 45, 58, 66, 75, 85, 90, 94, 98],
      chromaMultiplier: [0.12, 0.24, 0.4, 0.6, 1.0, 1.15, 1.1, 1.0, 0.85, 0.7, 0.55, 0.4],
      selector: ':root, [data-theme="light"]',
    },
    dark: {
      background: "#0b0d12",
      surface: "#14161d",
      onSurface: "#e8eaf0",
      targetLc: [3, 8, 15, 24, 34, 48, 62, 74, 84, 90, 94, 98],
      chromaMultiplier: [0.3, 0.55, 0.78, 0.95, 1.2, 1.1, 1.0, 0.8, 0.6, 0.5, 0.42, 0.36],
      selector: '[data-theme="dark"]',
    },
  },

  roles: [
    {
      key: "surfaceSubtle",
      label: "Surface subtle",
      index: { light: 0, dark: 0 },
      usage: "surface",
      requirement: "none",
      cssVar: "--color-{intent}-surface-subtle",
      description: "The quietest tinted background for this colour.",
    },
    {
      key: "surface",
      label: "Surface",
      index: { light: 1, dark: 1 },
      usage: "surface",
      requirement: "none",
      needsForeground: true,
      cssVar: "--color-{intent}-surface",
      foregroundCssVar: "--color-{intent}-on-surface",
      description: "Tinted background for banners, chips and quiet callouts.",
    },
    {
      key: "surfaceStrong",
      label: "Surface strong",
      index: { light: 2, dark: 2 },
      usage: "surface",
      requirement: "none",
      cssVar: "--color-{intent}-surface-strong",
      description: "Hover or raised state of the tinted surface.",
    },
    {
      key: "border",
      label: "Border",
      index: { light: 4, dark: 7 },
      usage: "boundary",
      requirement: "non-text",
      cssVar: "--color-{intent}-border",
      description: "Component outlines and focus rings. Answers to 1.4.11 at 3:1.",
    },
    {
      key: "fill",
      wantsSaturation: true,
      label: "Fill",
      index: { light: 6, dark: 4 },
      usage: "surface",
      requirement: "non-text",
      needsForeground: true,
      cssVar: "--color-{intent}-fill",
      foregroundCssVar: "--color-{intent}-on-fill",
      description: "Solid interactive surface: primary buttons, filled badges.",
    },
    {
      key: "text",
      label: "Text",
      index: { light: 7, dark: 6 },
      usage: "text",
      requirement: "body",
      cssVar: "--color-{intent}-text",
      description: "Coloured text and icons on the page background. Answers to 1.4.3 at 4.5:1.",
    },
  ],

  separationRoles: ["surface", "fill", "text"],

  cssHeader: "/* Generated by Colour Forge. Review before committing. */",

  seedPaletteLabel: "Material 500",
  seedPalette: MATERIAL_500,
};

/** The comparison family, derived from MUI's default intent colours.
 *
 *  Better than an invented example set for the reason Diamond's family is
 *  useful: it is a palette applications actually ship, so "does my new colour
 *  collide with anything" is being asked against something real. MUI does not
 *  publish per-role values for the roles in this profile, so the roles are
 *  generated here from its `main` colours by the same solver everything else
 *  goes through — derived, and labelled as derived, rather than presented as
 *  values MUI ships. */
function muiDefaultFamily(profile: Omit<Profile, "family">): SeededIntent[] {
  const withoutFamily: Profile = { ...profile, family: [] };
  return MUI_DEFAULT_INTENTS.map(({ name, hex }) => {
    const draft = buildDraft(withoutFamily, name, hex);
    const forMode = (mode: "light" | "dark"): Record<string, string> =>
      Object.fromEntries(Object.entries(draft[mode].roles).map(([key, step]) => [key, step.hex]));
    // These rows carry a recipe because this tool really did generate them,
    // so the family can be re-derived under different settings the same way a
    // draft can. Diamond's shipped intents deliberately have none.
    return {
      name,
      recipe: { seed: hex, policy: "wcag-strict", fillPlacement: "fixed" },
      light: forMode("light"),
      dark: forMode("dark"),
    };
  });
}

export const genericProfile: Profile = { ...base, family: muiDefaultFamily(base) };
