import { buildDraft } from "../color/scale";
import { MATERIAL_500, MUI_DEFAULT_INTENTS } from "./material";
import type { Profile, SeededIntent } from "./types";

/** A design-system-agnostic role set.
 *
 *  Six roles most token systems have some version of, named for how they
 *  are used rather than for any one library's vocabulary, laid out in the
 *  same broad zones Radix's scale uses — surface, container, solid, text —
 *  since that convention is now familiar enough to be worth matching.
 *
 *  The curve (`targetLc`, `chromaMultiplier`) is shared with every other
 *  profile: one scale, tuned once against a sweep of Material's 19 hues to
 *  keep any two steps from converging on the same colour. A profile's
 *  character comes from its token names and which step each role claims,
 *  never from a bespoke curve.
 *
 *  Most roles claim the same step in both modes. `container` and `solid`
 *  are the exception, carried over from Diamond's real, hand-tuned tokens:
 *  a large filled shape (`solid`) reads as itself from chroma alone and
 *  wants less luminance separation in dark mode, while the smaller,
 *  quieter role beside it needs more — so the two swap which one sits
 *  further out as the mode flips. */
const base: Omit<Profile, "family"> = {
  id: "generic",
  name: "Generic (design-system agnostic)",
  description:
    "Six usage-named roles and a neutral CSS naming convention. The starting point when you are not working in a system the tool already knows.",
  provenance:
    "Curves are a reasoned starting point — adjust the targets to match your own tokens. The comparison family is derived by this tool from MUI's default intent colours (Material Design 2), run through the same solver as everything else on the page.",
  scaleSize: 12,

  modes: {
    light: {
      background: "#fbfbfd",
      surface: "#ffffff",
      onSurface: "#16181d",
      targetLc: [3, 8, 16, 30, 45, 58, 66, 75, 85, 90, 94, 98],
      chromaMultiplier: [0.12, 0.24, 0.4, 0.6, 1.0, 1.15, 1.1, 1.0, 0.9, 0.8, 0.68, 0.55],
      selector: ':root, [data-theme="light"]',
    },
    dark: {
      background: "#0b0d12",
      surface: "#14161d",
      onSurface: "#e8eaf0",
      targetLc: [3, 8, 15, 24, 34, 48, 62, 74, 84, 90, 94, 98],
      chromaMultiplier: [0.3, 0.55, 0.78, 0.95, 1.2, 1.1, 1.0, 0.85, 0.75, 0.65, 0.55, 0.45],
      selector: '[data-theme="dark"]',
    },
  },

  roles: [
    {
      key: "surfaceSubtle",
      label: "Surface subtle",
      index: { light: 0, dark: 0 },
      usage: "surface",
      requirement: "none",
      cssVar: "--color-{intent}-surface-subtle",
      description: "The quietest tinted background for this colour.",
    },
    {
      key: "surface",
      label: "Surface",
      index: { light: 1, dark: 1 },
      usage: "surface",
      requirement: "none",
      needsForeground: true,
      cssVar: "--color-{intent}-surface",
      foregroundCssVar: "--color-{intent}-on-surface",
      description: "Tinted background for banners, chips and quiet callouts.",
    },
    {
      key: "surfaceStrong",
      label: "Surface strong",
      index: { light: 2, dark: 2 },
      usage: "surface",
      requirement: "none",
      cssVar: "--color-{intent}-surface-strong",
      description: "Hover or raised state of the tinted surface.",
    },
    {
      key: "container",
      label: "Container",
      index: { light: 4, dark: 7 },
      usage: "surface",
      requirement: "none",
      cssVar: "--color-{intent}-container",
      description:
        "Tinted component background between the page surface and the solid fill — hover states, secondary buttons, chip backgrounds.",
    },
    {
      key: "solid",
      label: "Solid",
      index: { light: 6, dark: 4 },
      usage: "surface",
      requirement: "non-text",
      needsForeground: true,
      cssVar: "--color-{intent}-solid",
      foregroundCssVar: "--color-{intent}-on-solid",
      description: "Solid interactive surface: primary buttons, filled badges. Answers to 1.4.11 at 3:1.",
    },
    {
      key: "text",
      label: "Text",
      index: { light: 9, dark: 9 },
      usage: "text",
      requirement: "body",
      cssVar: "--color-{intent}-text",
      description: "Coloured text and icons on the page background. Answers to 1.4.3 at 4.5:1.",
    },
  ],

  separationRoles: ["surface", "solid", "text"],

  cssHeader: "/* Generated by Colour Forge. Review before committing. */",

  seedPaletteLabel: "Material 500",
  seedPalette: MATERIAL_500,
};

/** The comparison family, derived from MUI's default intent colours.
 *
 *  Better than an invented example set for the reason Diamond's family is
 *  useful: it is a palette applications actually ship, so "does my new colour
 *  collide with anything" is being asked against something real. MUI does not
 *  publish per-role values for the roles in this profile, so the roles are
 *  generated here from its `main` colours by the same solver everything else
 *  goes through — derived, and labelled as derived, rather than presented as
 *  values MUI ships. */
function muiDefaultFamily(profile: Omit<Profile, "family">): SeededIntent[] {
  const withoutFamily: Profile = { ...profile, family: [] };
  return MUI_DEFAULT_INTENTS.map(({ name, hex }) => {
    const draft = buildDraft(withoutFamily, name, hex);
    const forMode = (mode: "light" | "dark"): Record<string, string> =>
      Object.fromEntries(Object.entries(draft[mode].roles).map(([key, step]) => [key, step.hex]));
    return { name, light: forMode("light"), dark: forMode("dark") };
  });
}

export const genericProfile: Profile = { ...base, family: muiDefaultFamily(base) };
