import { buildDraft } from "../color/scale";
import { MATERIAL_500, MUI_DEFAULT_INTENTS } from "./material";
import { BASELINE_BACKGROUND, type Profile, type SeededIntent } from "./types";

/** MUI / Material Design 2 — the palette most non-Diamond work already ships.
 *
 *  Role names and the CSS custom property convention are MUI's own: a
 *  `PaletteColor` is `{ light, main, dark, contrastText }`, and MUI's
 *  CssVarsProvider exposes exactly those under
 *  `--mui-palette-{intent}-{light,main,dark,contrastText}`. There is no
 *  `surface`/`container`/`text` here — MUI does not ship those for an
 *  arbitrary palette colour, so this profile does not invent them.
 *
 *  The curve (`targetLc`, `chromaMultiplier`) is shared with every other
 *  profile: one scale, tuned once against a sweep of Material's 19 hues to
 *  keep any two steps from converging on the same colour.
 *
 *  `main` sits at the same step MUI's role played under the old six-role
 *  model (`solid`), keeping its already-validated accessibility behaviour.
 *  `light` and `dark` are MUI's tonal offset either side of it — always a
 *  paler and a deeper pigment than `main`, regardless of theme — which is
 *  exactly the `container`/`solid` swap this tool already uses elsewhere,
 *  just applied to three roles instead of two: a pigment nearer white reads
 *  as quiet against a light page (low index) but stands out sharply against
 *  a dark one (high index), and a pigment nearer black does the reverse. So
 *  `light` and `dark` swap which one sits further out as the mode flips,
 *  with `main` fixed between them. */
const base: Omit<Profile, "family"> = {
  id: "mui",
  name: "MUI / Material Design 2",
  description:
    "MUI's own light/main/dark/contrastText palette shape and --mui-palette-* naming, seeded from Material Design 2 and checked against MUI's own default intents. For work already built on MUI, or starting from Material's palette.",
  provenance:
    "Curves are a reasoned starting point — adjust the targets to match your own tokens. The comparison family is derived by this tool from MUI's default intent colours (Material Design 2), run through the same solver as everything else on the page.",
  scaleSize: 12,

  /** MUI computes `contrastText` itself (black or white, by contrast
   *  threshold) — it has no notion of "the page's neutral text colour" the
   *  way a `themeText` candidate assumes, so that generic fallback doesn't
   *  fit here. White/Black/On-{role}/Tinted still do. */
  excludeForegroundCandidates: ["themeText"],

  modes: {
    light: {
      background: BASELINE_BACKGROUND.light,
      surface: "#ffffff",
      onSurface: "#16181d",
      targetLc: [3, 8, 16, 30, 45, 58, 66, 75, 85, 90, 94, 98],
      chromaMultiplier: [0.12, 0.24, 0.4, 0.6, 1.0, 1.15, 1.1, 1.0, 0.9, 0.8, 0.68, 0.55],
      selector: ':root, [data-theme="light"]',
    },
    dark: {
      background: BASELINE_BACKGROUND.dark,
      surface: "#14161d",
      onSurface: "#e8eaf0",
      targetLc: [3, 8, 15, 24, 34, 48, 62, 74, 84, 90, 94, 98],
      chromaMultiplier: [0.3, 0.55, 0.78, 0.95, 1.2, 1.1, 1.0, 0.85, 0.75, 0.65, 0.55, 0.45],
      selector: '[data-theme="dark"]',
    },
  },

  roles: [
    {
      key: "light",
      label: "Light",
      index: { light: 4, dark: 7 },
      usage: "surface",
      requirement: "none",
      cssVar: "--mui-palette-{intent}-light",
      description: "MUI's lightened tonal offset of main — hover backgrounds, subtle fills.",
    },
    {
      key: "main",
      label: "Main",
      index: { light: 6, dark: 4 },
      usage: "surface",
      requirement: "non-text",
      needsForeground: true,
      cssVar: "--mui-palette-{intent}-main",
      foregroundCssVar: "--mui-palette-{intent}-contrastText",
      description:
        "The intent's base colour: contained buttons, filled chips, coloured icons and text. Pairs with contrastText. Answers to 1.4.11 at 3:1.",
    },
    {
      key: "dark",
      label: "Dark",
      index: { light: 8, dark: 3 },
      usage: "surface",
      requirement: "none",
      cssVar: "--mui-palette-{intent}-dark",
      description: "MUI's darkened tonal offset of main — pressed and active states.",
    },
  ],

  separationRoles: ["light", "main", "dark"],

  cssHeader: "/* Generated by Colour Forge. Review before committing. */",

  scaleCssPrefix: "--mui-palette",

  seedPaletteLabel: "Material 500",
  seedPalette: MATERIAL_500,
};

/** The comparison family, derived from MUI's default intent colours.
 *
 *  Better than an invented example set for the reason Diamond's family is
 *  useful: it is a palette applications actually ship, so "does my new colour
 *  collide with anything" is being asked against something real. MUI does not
 *  publish per-role values for the roles in this profile, so the roles are
 *  generated here from its `main` colours by the same solver everything else
 *  goes through — derived, and labelled as derived, rather than presented as
 *  values MUI ships. */
function muiDefaultFamily(profile: Omit<Profile, "family">): SeededIntent[] {
  const withoutFamily: Profile = { ...profile, family: [] };
  return MUI_DEFAULT_INTENTS.map(({ name, hex }) => {
    const draft = buildDraft(withoutFamily, name, hex);
    const forMode = (mode: "light" | "dark"): Record<string, string> =>
      Object.fromEntries(Object.entries(draft[mode].roles).map(([key, step]) => [key, step.hex]));
    return { name, light: forMode("light"), dark: forMode("dark") };
  });
}

export const muiProfile: Profile = { ...base, family: muiDefaultFamily(base) };
